import { Article } from './article';

// export const ARTICLES: Article[] = [
//   { id: 1, heading: "Bitcoin Price Pattern Hints at Short-Term Rally to $4K", shortDescription: "Bitcoin’s overnight pullback from three-week highs hit on Friday doesn’t mean the rally is over.", content: "View\r\nBitcoin has backed off 4 percent from three-week highs seen on Friday, but looks to have formed a bull flag a bullish continuation pattern on the 4-hour chart.\r\nA move above $3,630 would confirm a flag breakout and open the doors to $4,000", imageUrl: "assets/images/article1.jpg", addDate: new Date("2019-02-12T11:20:03Z"), author: "Omkar Godbole", sourceUrl: "", source: "BBC" },
//   { id: 2, heading: "Higher Prices Are Back at Whole Foods - The Wall Street Journal", shortDescription: "Whole Foods is raising prices again. Amazon slashed prices after acquiring the natural grocer in 2017, but pressure from consumer-product makers has led Whole Foods to raise prices on hundreds of products.", content: "Whole Foods is raising prices again. Amazon.com Inc. AMZN 0.18% slashed prices at Whole Foods after acquiring the natural grocer in 2017, aiming to counter its reputation for high costs. Now, pressure from consumer-product makers to cover rising costs for pac", imageUrl: "assets/images/article2.jpg", addDate: new Date("2019-02-12T10:32:00Z"), author: "Heather Haddon", sourceUrl: "", source: "BBC" },
//   { id: 3, heading: "Go Ahead and Break Your Streak", shortDescription: "Photo: ivanacoi We’ve tried lots of techniques over the years to solidify a new habit. Tying up your ego in a daily streak is just one of those, and it’s not for everybody.", content: "Weve tried lots of techniques over the years to solidify a new habit. Tying up your ego in a daily streak is just one of those, and its not for everybody. And yet it seems every app wants you to care deeply about keeping up a consistent streak. Screw that. It", imageUrl: "assets/images/article3.jpg", addDate: new Date("2019-02-11T17:00:00Z"), author: "Beth Skwarecki on Vitals, shared by Beth Skwarecki to Lifehacker", sourceUrl: "", source: "BBC" },
//   { id: 4, heading: "Techstars and Starburst Aerospace are launching a space industry accelerator in Los Angeles", shortDescription: "With the help of NASA’s Jet Propulsion Lab, the U.S. Air Force, Lockheed Martin, Maxar Technologies, SAIC and the Israel Aerospace Industries company, Techstars and Starburst Aerospace are launching an accelerator focused on the space industry in Los Angeles.…", content: "With the help of NASA’s Jet Propulsion Lab, the U.S. Air Force, Lockheed Martin, Maxar Technologies, SAIC and the Israel Aerospace Industries company, Techstars and Starburst Aerospace are launching an accelerator focused on the space industry in Los Angeles.", imageUrl: "assets/images/article4.jpg", addDate: new Date("2019-02-12T09:22:47Z"), author: "Jonathan Shieber", sourceUrl: "", source: "BBC" },
//   { id: 10, heading: "Techstars and Starburst Aerospace are launching a space industry accelerator in Los Angeles", shortDescription: "With the help of NASA’s Jet Propulsion Lab, the U.S. Air Force, Lockheed Martin, Maxar Technologies, SAIC and the Israel Aerospace Industries company, Techstars and Starburst Aerospace are launching an accelerator focused on the space industry in Los Angeles.…", content: "With the help of NASA’s Jet Propulsion Lab, the U.S. Air Force, Lockheed Martin, Maxar Technologies, SAIC and the Israel Aerospace Industries company, Techstars and Starburst Aerospace are launching an accelerator focused on the space industry in Los Angeles.", imageUrl: "assets/images/article4.jpg", addDate: new Date("2019-02-12T09:22:47Z"), author: "Jonathan Shieber", sourceUrl: "", source: "onliner" },
//   { id: 11, heading: "Techstars and Starburst Aerospace are launching a space industry accelerator in Los Angeles", shortDescription: "With the help of NASA’s Jet Propulsion Lab, the U.S. Air Force, Lockheed Martin, Maxar Technologies, SAIC and the Israel Aerospace Industries company, Techstars and Starburst Aerospace are launching an accelerator focused on the space industry in Los Angeles.…", content: "With the help of NASA’s Jet Propulsion Lab, the U.S. Air Force, Lockheed Martin, Maxar Technologies, SAIC and the Israel Aerospace Industries company, Techstars and Starburst Aerospace are launching an accelerator focused on the space industry in Los Angeles.", imageUrl: "assets/images/article4.jpg", addDate: new Date("2019-02-12T09:22:47Z"), author: "Jonathan Shieber", sourceUrl: "", source: "onliner" },
//   { id: 12, heading: "Techstars and Starburst Aerospace are launching a space industry accelerator in Los Angeles", shortDescription: "With the help of NASA’s Jet Propulsion Lab, the U.S. Air Force, Lockheed Martin, Maxar Technologies, SAIC and the Israel Aerospace Industries company, Techstars and Starburst Aerospace are launching an accelerator focused on the space industry in Los Angeles.…", content: "With the help of NASA’s Jet Propulsion Lab, the U.S. Air Force, Lockheed Martin, Maxar Technologies, SAIC and the Israel Aerospace Industries company, Techstars and Starburst Aerospace are launching an accelerator focused on the space industry in Los Angeles.", imageUrl: "assets/images/article4.jpg", addDate: new Date("2019-02-12T09:22:47Z"), author: "Jonathan Shieber", sourceUrl: "", source: "onliner" }
// ];